version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 1.1.0
    commands:
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - sudo apt-get update && sudo apt-get install terraform
      - echo "Installing AWS CLI..."
      - apt-get update && apt-get install -y awscli
  pre_build:
    commands:
      - echo "Downloading Terraform Provider Plugins..."
      - terraform init -backend=false
  build:
    commands:
      - echo "Running Terraform Apply..."
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "Deployment Complete!"
